# SITE CONFIGURATION
title: Refactoring Life # your site title
author: Kumar Abhijeet # You :P
description: > # Meta description of Homepage
  It's a blog about life, software and productivity.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://refactoringlife.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Kumar Abhijeet
  links:
    - https://twitter.com/kumarabhijeet3
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/kumar1202
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
 A blog about life, software and productivity.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: kumarabhijeet1202@gmail.com # email for form submission

twitter_username: kumarabhijeet3 # replace with your_twitter_username or comment to remove link from footer
github_username:  kumar1202 # replace with your_github_username or comment to remove link from footer
instagram_username: kumar__abhijeet # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
